version: '3'

services:
  applications:
    image: tianon/true
    volumes:
      - "./data/logs:/var/log/nginx"

  logs:
    image: wtee
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "./data/logs:/var/log"
    environment:
      - LOGPATH=/var/log/nginx

  nginx:
    image: nginx
    tty: true
    ports:
      - "8081:80"
    volumes_from:
      - applications

